import type { SchemaManifest, SchemaObject, SchemaRelation } from "./types.js";

/**
 * Every custom Twenty object and field the dialer reads or writes, taken from
 * the live workspace metadata (labels, types, nullability, defaults and
 * SELECT options exactly as live). applySchema() creates whatever is missing,
 * so a fresh workspace ends up with this shape.
 *
 * Left out on purpose: Twenty's standard fields (id, name, createdAt, ...),
 * fields no dialer code touches (the live objects carry more, owned by other
 * pipelines), and relations to objects the dialer does not use
 * (agencyMessage, agencyOpportunity). No metadata ids: they differ per
 * workspace.
 *
 * agencyCall.disposition mirrors DISPOSITION_OPTIONS in lib/twenty/agencyCall.
 */
export const SCHEMA_OBJECTS: SchemaObject[] = [
  {
    nameSingular: "agencyProspect",
    namePlural: "agencyProspects",
    labelSingular: "Agency Prospect",
    labelPlural: "Agency Prospects",
    description: "Local-service leads ingested for industry-labelled template sites",
    icon: "IconBuildingStore",
    fields: [
      { name: "brandColors", type: "RAW_JSON", label: "Brand Colors", description: "Logo-derived palette: { primary, palette[] }. primary drives BRAND_COLOR; null when the logo has no usable brand color." },
      { name: "city", type: "TEXT", label: "City", description: "City", isNullable: false },
      { name: "coldCallStatus", type: "SELECT", label: "Cold Call Status", description: "Status from manual cold calling workflow (separate from SMS outbound pipeline)", options: [
        { value: "NEW", label: "New", color: "gray" },
        { value: "CONTACTED", label: "Contacted", color: "blue" },
        { value: "INTERESTED", label: "Interested", color: "green" },
        { value: "NOT_INTERESTED", label: "Not Interested", color: "red" },
        { value: "CALLBACK", label: "Callback", color: "yellow" },
        { value: "CONVERTED", label: "Converted", color: "purple" },
        { value: "DO_NOT_CONTACT", label: "Do Not Contact", color: "black" },
      ] },
      { name: "country", type: "TEXT", label: "Country", description: "Country code or name", isNullable: false },
      { name: "createdByMemberId", type: "TEXT", label: "Created By Member ID" },
      { name: "email", type: "TEXT", label: "Email", description: "Primary email" },
      { name: "externalId", type: "TEXT", label: "External ID", description: "Stable external id (e.g. lead-pipeline uuid) for deduplication" },
      { name: "fullAddress", type: "TEXT", label: "Full Address", description: "Full formatted address from the lead list", isNullable: false },
      { name: "ghlWebhookUrl", type: "TEXT", label: "GHL Webhook URL", description: "GoHighLevel inbound webhook for lead forms (disconnected by default)" },
      { name: "googleReviewsUrl", type: "TEXT", label: "Google Reviews URL", description: "Public URL to the business Google reviews / Maps listing" },
      { name: "label", type: "SELECT", label: "Industry", description: "Industry segment used to pick a template site", isNullable: false, defaultValue: "'AUTO_PAINT_AND_BODY_SHOPS'", options: [
        { value: "AUTO_PAINT_AND_BODY_SHOPS", label: "Auto Paint & Body Shop", color: "orange" },
        { value: "WINDOW_TINTING", label: "Window Tinting", color: "blue" },
        { value: "AUTO_DETAILING", label: "Auto Detailing", color: "turquoise" },
        { value: "GENERAL_TRADES", label: "General Trades", color: "gray" },
        { value: "NURSERY_SCHOOL", label: "Nursery School", color: "purple" },
      ] },
      { name: "logoUrl", type: "TEXT", label: "Logo URL", description: "HTTPS URL for the business logo (site icon / favicon). Not a Twenty FILES blob — the template <img> loads this URL." },
      { name: "niche", type: "TEXT", label: "Niche", description: "Source industry string from the lead list", isNullable: false },
      { name: "notes", type: "TEXT", label: "Notes" },
      { name: "outboundLabel", type: "SELECT", label: "Outbound Label", description: "Presentation/filter label derived from outboundState. Stored separately from smsMetadata so Twenty can filter, group, and build views from first-class fields.", options: [
        { value: "NEEDS_ENRICHMENT", label: "Needs Enrichment", color: "gray" },
        { value: "NEEDS_VIDEO", label: "Needs Video", color: "gray" },
        { value: "READY_FOR_SMS", label: "Ready For SMS", color: "turquoise" },
        { value: "SMS_IN_PROGRESS", label: "SMS In Progress", color: "blue" },
        { value: "FOLLOW_UP_DUE", label: "Follow Up Due", color: "yellow" },
        { value: "HUMAN_REVIEW", label: "Human Review", color: "purple" },
        { value: "POSITIVE_REPLY", label: "Positive Reply", color: "green" },
        { value: "NEGATIVE_REPLY", label: "Negative Reply", color: "red" },
        { value: "DO_NOT_CONTACT", label: "Do Not Contact", color: "red" },
        { value: "DELIVERY_FAILED", label: "Delivery Failed", color: "red" },
      ] },
      { name: "outboundState", type: "SELECT", label: "Outbound State", description: "Lifecycle position of the prospect in the outbound SMS state machine. See declarative label/state contract.", options: [
        { value: "NEW", label: "New", color: "gray" },
        { value: "ENRICHED", label: "Enriched", color: "blue" },
        { value: "VIDEO_READY", label: "Video Ready", color: "blue" },
        { value: "QUEUED", label: "Queued", color: "turquoise" },
        { value: "SENDING", label: "Sending", color: "blue" },
        { value: "AWAITING_DELIVERY", label: "Awaiting Delivery", color: "blue" },
        { value: "AWAITING_REPLY", label: "Awaiting Reply", color: "blue" },
        { value: "REPLIED", label: "Replied", color: "purple" },
        { value: "QUALIFIED", label: "Qualified", color: "green" },
        { value: "BOOKED", label: "Booked", color: "green" },
        { value: "COMPLETED", label: "Completed", color: "green" },
        { value: "PAUSED", label: "Paused", color: "yellow" },
        { value: "OPTED_OUT", label: "Opted Out", color: "red" },
        { value: "FAILED", label: "Failed", color: "red" },
      ] },
      { name: "phone", type: "TEXT", label: "Phone", description: "Primary phone in E.164 or source format", isNullable: false },
      { name: "phoneNumber", type: "PHONES", label: "Phone Number", description: "Contact-identity composite — parity with Person.phones. Subfields: primaryPhoneNumber, primaryPhoneCountryCode, primaryPhoneCallingCode, additionalPhones. Not the SMS ledger; the evolving SMS state lives in smsMetadata." },
      { name: "phoneValid", type: "BOOLEAN", label: "Phone Valid", description: "False when WhatsApp validation rejects the number; true when it passes" },
      { name: "primaryEmail", type: "EMAILS", label: "Primary Email", description: "Primary contact email — parity with Person.emails. Structured email storage." },
      { name: "primaryPhone", type: "PHONES", label: "Primary Phone", description: "Contact-identity composite — parity with Person.phones. Subfields: primaryPhoneNumber, primaryPhoneCountryCode, primaryPhoneCallingCode, additionalPhones." },
      { name: "qualificationStatus", type: "SELECT", label: "Qualification Status", description: "Qualified or Disqualified", options: [
        { value: "QUALIFIED", label: "Qualified", color: "green" },
        { value: "DISQUALIFIED", label: "Disqualified", color: "red" },
      ] },
      { name: "rating", type: "NUMBER", label: "Rating", description: "Average review rating" },
      { name: "region", type: "TEXT", label: "Region", description: "State or region", isNullable: false },
      { name: "reviewCount", type: "NUMBER", label: "Review Count", description: "Number of reviews" },
      { name: "reviews", type: "RAW_JSON", label: "Reviews", description: "Up to a few real Google review snippets: [{ name, text, rating?, vehicle? }]. Never invent — feeds REVIEW_* template tokens." },
      { name: "slug", type: "TEXT", label: "Slug", description: "URL-safe identifier for the template site", isNullable: false },
      { name: "smsMetadata", type: "RAW_JSON", label: "SMS Metadata", description: "Evolving SMS lifecycle payload (schemaVersion, consent, sequence, provider state). RAW_JSON — Twenty has no native JSON composite type. Not the message ledger; per-message delivery status goes in native Message records later." },
      { name: "utmSource", type: "SELECT", label: "UTM Source", options: [
        { value: "OUTBOUND", label: "Outbound", color: "blue" },
        { value: "INBOUND", label: "Inbound", color: "green" },
        { value: "BLENDED", label: "Blended", color: "purple" },
      ] },
      { name: "videoError", type: "TEXT", label: "Video Error", description: "Message describing why the video run failed, cleared on the next successful run" },
      { name: "videoSource", type: "TEXT", label: "Video Source", description: "Where the produced walkthrough video lives (path under public/robovsl or an attached URL)" },
      { name: "videoStatus", type: "SELECT", label: "Video Status", description: "Lifecycle of the cap-video walkthrough for this lead: None → Queued → Recording → Rendered → Attached, or Failed", options: [
        { value: "NONE", label: "None", color: "gray" },
        { value: "QUEUED", label: "Queued", color: "gray" },
        { value: "RECORDING", label: "Recording", color: "blue" },
        { value: "RENDERED", label: "Rendered", color: "purple" },
        { value: "ATTACHED", label: "Attached", color: "green" },
        { value: "FAILED", label: "Failed", color: "red" },
      ] },
      { name: "videoUrl", type: "LINKS", label: "Video URL", description: "Public URL of the produced cap-video walkthrough. Composite subfields: primaryLinkUrl, primaryLinkLabel, secondaryLinks." },
      { name: "website", type: "TEXT", label: "Website", description: "Business website URL", isNullable: false },
      { name: "whatsappStatus", type: "SELECT", label: "WhatsApp Status", description: "Pending until checked; Validated if the number is on WhatsApp; Rejected if it is not", options: [
        { value: "PENDING", label: "Pending", color: "gray" },
        { value: "VALIDATED", label: "Validated", color: "green" },
        { value: "REJECTED", label: "Rejected", color: "red" },
      ] },
      { name: "whatsappValidated", type: "BOOLEAN", label: "WhatsApp Validated", description: "True when the WhatsApp check confirms the number is registered" },
    ],
  },
  {
    nameSingular: "agencyLead",
    namePlural: "agencyLeads",
    labelSingular: "Agency Lead",
    labelPlural: "Agency Leads",
    description: "ListeningKit engaged prospect who responded to outreach. Created when an agencyProspect replies positively.",
    icon: "IconUserCheck",
    fields: [
      { name: "coldCallStatus", type: "SELECT", label: "Cold Call Status", description: "Status from manual cold calling workflow (separate from SMS outbound pipeline)", options: [
        { value: "NEW", label: "New", color: "gray" },
        { value: "CONTACTED", label: "Contacted", color: "blue" },
        { value: "INTERESTED", label: "Interested", color: "green" },
        { value: "NOT_INTERESTED", label: "Not Interested", color: "red" },
        { value: "CALLBACK", label: "Callback", color: "yellow" },
        { value: "CONVERTED", label: "Converted", color: "purple" },
        { value: "DO_NOT_CONTACT", label: "Do Not Contact", color: "black" },
      ] },
      { name: "contactName", type: "TEXT", label: "Contact Name", description: "Human contact person name" },
      { name: "email", type: "EMAILS", label: "Email", description: "Contact email" },
      { name: "note", type: "TEXT", label: "Note", description: "Initial conversation transcript" },
      { name: "outboundMessage", type: "TEXT", label: "Outbound Message", description: "The message we sent (for A/B testing)" },
      { name: "phone", type: "PHONES", label: "Phone", description: "Contact phone number" },
      { name: "qualificationStatus", type: "SELECT", label: "Qualification Status", description: "Qualified or Disqualified from quiz", options: [
        { value: "QUALIFIED", label: "Qualified", color: "green" },
        { value: "DISQUALIFIED", label: "Disqualified", color: "red" },
      ] },
      { name: "source", type: "TEXT", label: "Source", description: "How they engaged (sms-reply, form-submit, call-inbound)" },
      { name: "status", type: "SELECT", label: "Status", description: "NEW / CONTACTED / QUALIFIED / BOOKED / CONVERTED / LOST", options: [
        { value: "NEW", label: "New", color: "gray" },
        { value: "CONTACTED", label: "Contacted", color: "blue" },
        { value: "QUALIFIED", label: "Qualified", color: "purple" },
        { value: "BOOKED", label: "Booked", color: "green" },
        { value: "CONVERTED", label: "Converted", color: "emerald" },
        { value: "LOST", label: "Lost", color: "red" },
      ] },
    ],
  },
  {
    nameSingular: "agencyCampaign",
    namePlural: "agencyCampaigns",
    labelSingular: "Agency Campaign",
    labelPlural: "Agency Campaigns",
    description: "Campaign that drives traffic to a prospect-specific offer page.",
    icon: "Flag",
    fields: [
      { name: "campaignType", type: "SELECT", label: "Campaign Type", options: [
        { value: "OUTBOUND", label: "Outbound", color: "blue" },
        { value: "INBOUND", label: "Inbound", color: "green" },
        { value: "BLENDED", label: "Blended", color: "purple" },
        { value: "REFERRAL", label: "Referral", color: "amber" },
        { value: "COLD_CALL", label: "Cold Call", color: "red" },
        { value: "WEBSITE", label: "Website", color: "cyan" },
        { value: "TWENTY_IMPORT", label: "Twenty Import", color: "gray" },
        { value: "OTHER", label: "Other", color: "gray" },
      ] },
      { name: "funnelBaseUrl", type: "TEXT", label: "Funnel Base URL", description: "Host serving the bare offer funnel (/offer/prospect/:id). Runtime reads this row — never hardcoded." },
      { name: "industryId", type: "SELECT", label: "Industry", description: "Industry this campaign owns (mirrors prospect label values).", options: [
        { value: "AUTO_PAINT_AND_BODY_SHOPS", label: "Auto Body", color: "orange" },
        { value: "WINDOW_TINTING", label: "Window Tint", color: "blue" },
        { value: "AUTO_DETAILING", label: "Detailing", color: "turquoise" },
        { value: "GENERAL_TRADES", label: "General Trades", color: "gray" },
        { value: "NURSERY_SCHOOL", label: "Nursery School", color: "purple" },
      ] },
      { name: "packDir", type: "TEXT", label: "Pack Dir", description: "Template pack folder for this industry (video-agent --pack-dir)." },
      { name: "status", type: "SELECT", label: "Status", icon: "IconTag", options: [
        { value: "ACTIVE", label: "ACTIVE", color: "green" },
        { value: "INACTIVE", label: "INACTIVE", color: "red" },
        { value: "DRAFT", label: "DRAFT", color: "gray" },
      ] },
      { name: "templateBaseUrl", type: "TEXT", label: "Template Base URL", description: "Host serving the branded /offer/:industry/:slug shell. Runtime reads this row — never hardcoded." },
      { name: "urlKey", type: "TEXT", label: "URL Key", description: "Short industry key used in /offer/:industry/:slug URLs (autobody/tint/detailing/general)." },
      { name: "utmSource", type: "SELECT", label: "UTM Source", description: "Attribution source for the campaign funnel.", options: [
        { value: "OUTBOUND", label: "Outbound", color: "blue" },
        { value: "INBOUND", label: "Inbound", color: "emerald" },
        { value: "BLENDED", label: "Blended", color: "purple" },
      ] },
    ],
  },
  {
    nameSingular: "agencyScript",
    namePlural: "agencyScripts",
    labelSingular: "Script",
    labelPlural: "Scripts",
    description: "Call scripts for campaigns",
    icon: "IconFileText",
    fields: [
      { name: "scriptData", type: "TEXT", label: "Script Data", description: "JSON string containing script content and objection responses", settings: {} },
    ],
  },
  {
    nameSingular: "agencyPhone",
    namePlural: "agencyPhones",
    labelSingular: "Agency Phone",
    labelPlural: "Agency Phones",
    description: "Owned Telnyx phone numbers for outbound SMS — messaging profile, physical state, health",
    icon: "IconPhone",
    fields: [
      { name: "callState", type: "SELECT", label: "Call State", options: [
        { value: "IDLE", label: "Idle", color: "gray" },
        { value: "DIALING", label: "Dialing", color: "yellow" },
        { value: "ACTIVE", label: "Active", color: "green" },
      ] },
      { name: "claimedAt", type: "DATE_TIME", label: "Claimed At" },
      { name: "claimedByEmail", type: "TEXT", label: "Claimed By Email" },
      { name: "claimedByMemberId", type: "TEXT", label: "Claimed By Member" },
      { name: "countryCode", type: "TEXT", label: "Country Code", description: "ISO country code" },
      { name: "currentCallId", type: "TEXT", label: "Current Call" },
      { name: "eligibleProducts", type: "RAW_JSON", label: "Eligible Products", description: "eligible_messaging_products array from Telnyx" },
      { name: "features", type: "RAW_JSON", label: "Features", description: "Telnyx features object: { sms: true, mms: false, ... }" },
      { name: "health", type: "RAW_JSON", label: "Health", description: "Telnyx health object: { message_success_rate, ... }" },
      { name: "lastHeartbeatAt", type: "DATE_TIME", label: "Last Heartbeat At" },
      { name: "lastSyncedAt", type: "TEXT", label: "Last Synced At", description: "ISO timestamp of last Telnyx sync" },
      { name: "messagingProfileId", type: "TEXT", label: "Messaging Profile ID", description: "Telnyx messaging profile UUID" },
      { name: "numberType", type: "SELECT", label: "Number Type", description: "long_code, toll_free, or short_code", options: [
        { value: "LONG_CODE", label: "Long Code", color: "gray" },
        { value: "TOLL_FREE", label: "Toll Free", color: "blue" },
        { value: "SHORT_CODE", label: "Short Code", color: "purple" },
      ] },
      { name: "phoneNumber", type: "TEXT", label: "Phone Number", description: "E.164 phone number owned in Telnyx", isNullable: false },
      { name: "state", type: "SELECT", label: "State", description: "Operational state of the number", options: [
        { value: "ACTIVE", label: "Active", color: "green" },
        { value: "PAUSED", label: "Paused", color: "yellow" },
        { value: "DEGRADED", label: "Degraded", color: "orange" },
        { value: "RETIRED", label: "Retired", color: "red" },
      ] },
      { name: "tenDlcCampaignId", type: "TEXT", label: "10DLC Campaign ID", description: "10DLC campaign registration ID" },
      { name: "tollFreeVerificationId", type: "TEXT", label: "Toll-Free Verification ID", description: "Toll-free verification ID" },
    ],
  },
  {
    nameSingular: "agencyCall",
    namePlural: "agencyCalls",
    labelSingular: "Call",
    labelPlural: "Calls",
    description: "Outbound/inbound dialer calls: recording, transcript, relations to phone/prospect/lead, future meeting link.",
    icon: "IconPhoneCall",
    fields: [
      { name: "aiAnalyzedAt", type: "DATE_TIME", label: "Ai Analyzed At" },
      { name: "aiConfidence", type: "NUMBER", label: "Ai Confidence" },
      { name: "aiKeyPoints", type: "TEXT", label: "Ai Key Points" },
      { name: "aiModel", type: "TEXT", label: "Ai Model" },
      { name: "aiScore", type: "NUMBER", label: "Ai Score" },
      { name: "aiScores", type: "TEXT", label: "Ai Scores" },
      { name: "aiSentiment", type: "TEXT", label: "Ai Sentiment" },
      { name: "aiSummary", type: "TEXT", label: "Ai Summary" },
      { name: "createdByMemberId", type: "TEXT", label: "Created By Member ID" },
      { name: "debugLog", type: "TEXT", label: "Debug Log" },
      { name: "direction", type: "SELECT", label: "Direction", options: [
        { value: "INBOUND", label: "Inbound", color: "blue" },
        { value: "OUTBOUND", label: "Outbound", color: "green" },
        { value: "MISSED", label: "Missed", color: "red" },
      ] },
      { name: "disposition", type: "SELECT", label: "Disposition", description: "The operator's call outcome (status keeps the system result)", options: [
        { value: "INTERESTED", label: "Interested", color: "green" },
        { value: "APPOINTMENT_SET", label: "Appointment Set", color: "green" },
        { value: "CALLBACK", label: "Callback", color: "turquoise" },
        { value: "GOOD_NUMBER", label: "Good Number", color: "turquoise" },
        { value: "LEFT_CALLBACK", label: "Left Callback", color: "sky" },
        { value: "VOICEMAIL", label: "Left Voicemail", color: "sky" },
        { value: "NOT_INTERESTED", label: "Not Interested", color: "red" },
        { value: "BAD_NUMBER", label: "Bad Number", color: "red" },
        { value: "NO_ANSWER", label: "No Answer", color: "gray" },
        { value: "WRONG_NUMBER", label: "Wrong Number", color: "orange" },
        { value: "DNC", label: "Do Not Contact", color: "red" },
      ] },
      { name: "durationSeconds", type: "NUMBER", label: "Duration (s)" },
      { name: "endedAt", type: "DATE_TIME", label: "Ended At" },
      { name: "fromNumber", type: "TEXT", label: "From Number" },
      { name: "meetingAt", type: "DATE_TIME", label: "Meeting At" },
      { name: "meetingBookingId", type: "TEXT", label: "Meeting Booking ID" },
      { name: "meetingProvider", type: "SELECT", label: "Meeting Provider", options: [
        { value: "NONE", label: "None", color: "gray" },
        { value: "GOOGLE_MEET", label: "Google Meet", color: "blue" },
        { value: "ZOOM", label: "Zoom", color: "purple" },
        { value: "TEAMS", label: "Teams", color: "orange" },
        { value: "OTHER", label: "Other", color: "gray" },
      ] },
      { name: "meetingStatus", type: "SELECT", label: "Meeting Status", options: [
        { value: "NONE", label: "None", color: "gray" },
        { value: "SCHEDULED", label: "Scheduled", color: "blue" },
        { value: "HELD", label: "Held", color: "green" },
        { value: "CANCELLED", label: "Cancelled", color: "red" },
        { value: "NO_SHOW", label: "No Show", color: "orange" },
      ] },
      { name: "meetingUrl", type: "TEXT", label: "Meeting URL" },
      { name: "notes", type: "TEXT", label: "Notes" },
      { name: "recordingUrl", type: "TEXT", label: "Recording URL" },
      { name: "startedAt", type: "DATE_TIME", label: "Started At" },
      { name: "status", type: "SELECT", label: "Status", options: [
        { value: "IN_PROGRESS", label: "In Progress", color: "yellow" },
        { value: "COMPLETED", label: "Completed", color: "green" },
        { value: "FAILED", label: "Failed", color: "red" },
        { value: "NO_ANSWER", label: "No Answer", color: "orange" },
        { value: "BUSY", label: "Busy", color: "purple" },
      ] },
      { name: "summary", type: "TEXT", label: "Summary" },
      { name: "telnyxCallId", type: "TEXT", label: "Telnyx Call ID" },
      { name: "telnyxRecordingId", type: "TEXT", label: "Telnyx Recording ID" },
      { name: "toNumber", type: "TEXT", label: "To Number" },
      { name: "transcript", type: "TEXT", label: "Transcript" },
      { name: "transcriptionStatus", type: "SELECT", label: "Transcription", options: [
        { value: "NONE", label: "None", color: "gray" },
        { value: "PENDING", label: "Pending", color: "yellow" },
        { value: "READY", label: "Ready", color: "green" },
        { value: "FAILED", label: "Failed", color: "red" },
      ] },
    ],
  },
  {
    nameSingular: "agencyPerson",
    namePlural: "agencyPeople",
    labelSingular: "Agency Person",
    labelPlural: "Agency People",
    description: "A human contact at an agency prospect or lead - the person we talk to, not the company.",
    icon: "IconUser",
    fields: [
      { name: "avatarUrl", type: "TEXT", label: "Avatar URL" },
      { name: "city", type: "TEXT", label: "City" },
      { name: "emails", type: "EMAILS", label: "Emails", settings: {"maxNumberOfValues":1} },
      { name: "jobTitle", type: "TEXT", label: "Job Title" },
      { name: "linkedinLink", type: "LINKS", label: "LinkedIn" },
      { name: "personRole", type: "TEXT", label: "Role" },
      { name: "phones", type: "PHONES", label: "Phones", settings: {"maxNumberOfValues":1} },
      { name: "xLink", type: "LINKS", label: "X" },
    ],
  },
  {
    nameSingular: "agencyOffer",
    namePlural: "agencyOffers",
    labelSingular: "Agency Offer",
    labelPlural: "Agency Offers",
    description: "A guided one-page lander tied to a campaign — testimonials, CTA, video.",
    icon: "Gift",
    fields: [
      { name: "ctaType", type: "SELECT", label: "CTA Type", description: "CONSULTATION / PRICING / CUSTOM (Twenty requires UPPER_CASE values)", options: [
        { value: "CONSULTATION", label: "Consultation", color: "blue" },
        { value: "PRICING", label: "Pricing", color: "green" },
        { value: "CUSTOM", label: "Custom", color: "gray" },
      ] },
      { name: "heroH1", type: "TEXT", label: "Hero H1", description: "Hero section H1 heading" },
      { name: "heroLede", type: "RICH_TEXT", label: "Hero Lede", description: "Hero section lede paragraph" },
      { name: "industryId", type: "SELECT", label: "Industry", description: "Industry this offer serves (INDUSTRY:{id} rows).", options: [
        { value: "AUTO_PAINT_AND_BODY_SHOPS", label: "Auto Body", color: "orange" },
        { value: "WINDOW_TINTING", label: "Window Tint", color: "blue" },
        { value: "AUTO_DETAILING", label: "Detailing", color: "turquoise" },
        { value: "GENERAL_TRADES", label: "General Trades", color: "gray" },
      ] },
      { name: "status", type: "SELECT", label: "Status", description: "DRAFT / ACTIVE / PAUSED", options: [
        { value: "DRAFT", label: "Draft", color: "gray" },
        { value: "ACTIVE", label: "Active", color: "green" },
        { value: "PAUSED", label: "Paused", color: "yellow" },
      ] },
      { name: "title", type: "TEXT", label: "Title", description: "Offer title" },
      { name: "videoMode", type: "SELECT", label: "Video Source", description: "PROSPECT = use the prospect record videoUrl; CUSTOM = use this offer videoUrl for the whole industry.", options: [
        { value: "PROSPECT", label: "Prospect video", color: "blue" },
        { value: "CUSTOM", label: "Custom URL", color: "green" },
      ] },
      { name: "videoUrl", type: "LINKS", label: "Video URL", description: "VSL video URL" },
    ],
  },
  {
    nameSingular: "callCampaign",
    namePlural: "callCampaigns",
    labelSingular: "Call Campaign",
    labelPlural: "Call Campaigns",
    description: "Dial lists created from the dialer's Contacts page",
    icon: "IconPhoneOutgoing",
    fields: [
      { name: "contactIds", type: "TEXT", label: "Contact IDs" },
      { name: "createdByMemberId", type: "TEXT", label: "Created By Member ID" },
      { name: "ownerName", type: "TEXT", label: "Owner Name" },
      { name: "status", type: "TEXT", label: "Status" },
    ],
  },
  {
    nameSingular: "dialerAudioSession",
    namePlural: "dialerAudioSessions",
    labelSingular: "Dialer Audio Session",
    labelPlural: "Dialer Audio Sessions",
    description: "Phone audio lines (Call me / Dial in) used by the dialer",
    icon: "IconHeadset",
    fields: [
      { name: "agentLegId", type: "TEXT", label: "Agent Leg ID" },
      { name: "agentPhone", type: "TEXT", label: "Agent Phone" },
      { name: "contactAnsweredAt", type: "TEXT", label: "Contact Answered At" },
      { name: "contactEndedAt", type: "TEXT", label: "Contact Ended At" },
      { name: "contactLegId", type: "TEXT", label: "Contact Leg ID" },
      { name: "contactState", type: "TEXT", label: "Contact State" },
      { name: "error", type: "TEXT", label: "Error" },
      { name: "expiresAt", type: "TEXT", label: "Expires At" },
      { name: "hangupCause", type: "TEXT", label: "Hangup Cause" },
      { name: "memberId", type: "TEXT", label: "Member ID" },
      { name: "mode", type: "TEXT", label: "Mode" },
      { name: "pin", type: "TEXT", label: "Pin" },
      { name: "status", type: "TEXT", label: "Status" },
    ],
  },
  {
    // Shared with Blaster: TEXT fields and Telnyx's own status words.
    nameSingular: "agencyMessage",
    namePlural: "agencyMessages",
    labelSingular: "Agency Message",
    labelPlural: "Agency Messages",
    description: "SMS sent and received through Telnyx",
    icon: "IconMessage",
    fields: [
      { name: "body", type: "TEXT", label: "Body" },
      { name: "direction", type: "TEXT", label: "Direction" },
      { name: "fromNumber", type: "TEXT", label: "From Number" },
      { name: "toNumber", type: "TEXT", label: "To Number" },
      { name: "status", type: "TEXT", label: "Status" },
      { name: "telnyxMessageId", type: "TEXT", label: "Telnyx Message ID" },
      { name: "errorCode", type: "TEXT", label: "Error Code", description: "Telnyx error code when the text failed, e.g. 40010" },
      { name: "errorMessage", type: "TEXT", label: "Error Message", description: "Why the text failed, in Telnyx's words" },
    ],
  },
  {
    nameSingular: "agencyConversation",
    namePlural: "agencyConversations",
    labelSingular: "Agency Conversation",
    labelPlural: "Agency Conversations",
    description: "One SMS thread per pair of numbers (ours, theirs)",
    icon: "IconMessages",
    fields: [
      { name: "pairKey", type: "TEXT", label: "Pair Key" },
      { name: "peerPhone", type: "TEXT", label: "Peer Phone" },
      { name: "blasterNumber", type: "TEXT", label: "Blaster Number" },
      { name: "latestMessageId", type: "TEXT", label: "Latest Message ID" },
      { name: "latestMessageAt", type: "DATE_TIME", label: "Latest Message At" },
      { name: "latestPreview", type: "TEXT", label: "Latest Preview" },
      { name: "latestDirection", type: "TEXT", label: "Latest Direction" },
      { name: "messageCount", type: "NUMBER", label: "Message Count" },
    ],
  },
];

/** Created after every object exists, from the MANY_TO_ONE side. */
export const SCHEMA_RELATIONS: SchemaRelation[] = [
  {
    object: "agencyProspect",
    name: "campaignId",
    label: "Campaign",
    icon: "IconRelationOneToMany",
    target: "agencyCampaign",
    targetFieldName: "prospects",
    targetFieldLabel: "Prospects",
    targetFieldIcon: "IconFileText",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyLead",
    name: "person",
    label: "Person",
    icon: "IconRelationOneToMany",
    target: "agencyPerson",
    targetFieldName: "leads",
    targetFieldLabel: "Leads",
    targetFieldIcon: "IconUser",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyLead",
    name: "campaignId",
    label: "Campaign",
    icon: "IconRelationOneToMany",
    target: "agencyCampaign",
    targetFieldName: "leads",
    targetFieldLabel: "Leads",
    targetFieldIcon: "IconFileText",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyLead",
    name: "agencyProspect",
    label: "Agency Prospect",
    icon: "IconRelationOneToMany",
    target: "agencyProspect",
    targetFieldName: "agencyLeads",
    targetFieldLabel: "Agency Leads",
    targetFieldIcon: "IconUserCheck",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyScript",
    name: "campaignId",
    label: "Campaign",
    icon: "IconRelationOneToMany",
    target: "agencyCampaign",
    targetFieldName: "scripts",
    targetFieldLabel: "Scripts",
    targetFieldIcon: "IconFileText",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyCall",
    name: "agencyProspect",
    label: "Prospect",
    icon: "IconPhoneCall",
    target: "agencyProspect",
    targetFieldName: "calls",
    targetFieldLabel: "Calls",
    targetFieldIcon: "IconPhoneCall",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyCall",
    name: "agencyPhone",
    label: "Phone",
    icon: "IconPhoneCall",
    target: "agencyPhone",
    targetFieldName: "calls",
    targetFieldLabel: "Calls",
    targetFieldIcon: "IconPhoneCall",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyCall",
    name: "agencyLead",
    label: "Lead",
    icon: "IconPhoneCall",
    target: "agencyLead",
    targetFieldName: "calls",
    targetFieldLabel: "Calls",
    targetFieldIcon: "IconPhoneCall",
    onDelete: "SET_NULL",
  },
  {
    object: "agencyPerson",
    name: "prospect",
    label: "Prospect",
    icon: "IconUser",
    target: "agencyProspect",
    targetFieldName: "people",
    targetFieldLabel: "People",
    targetFieldIcon: "IconRelationOneToMany",
    onDelete: "SET_NULL",
  },
];

export const SCHEMA_MANIFEST: SchemaManifest = { objects: SCHEMA_OBJECTS, relations: SCHEMA_RELATIONS };
