// Pre-push gate: nothing out of the dialer's scope may be tracked in git.
//
// The repository deliberately keeps host-specific infrastructure, unrelated
// apps, vendored third-party skills, deploy staging output and credentials on
// local machines instead of in the tracked tree. This check fails the moment
// one of them gets added back, which is how they got there in the first place.
//
// Bypass for emergencies only:
//   SKIP_SCOPE_CHECK=1 git push
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

if (process.env.SKIP_SCOPE_CHECK) {
  console.log('pre-push: SKIP_SCOPE_CHECK set, skipping scope check.');
  process.exit(0);
}

// Path prefixes and exact files that must never be tracked, with the reason.
const OUT_OF_SCOPE = [
  ['ops/', 'host-specific node01 infrastructure and tailnet addresses'],
  ['matthew-onboarding/', 'an unrelated Railcode app'],
  ['agent/', 'vendored external agent skills'],
  ['.agents/', 'vendored external agent skills'],
  ['.claude/', 'vendored external agent skills'],
  ['twenty-native-app/src/skills/', 'vendored third-party skill definitions'],
  ['hostinger/', 'deploy staging output, regenerated by scripts/deploy.sh'],
  ['docs/telnyx/upstream/', 'mirrored upstream docs, see scripts/pull-telnyx-docs.mjs'],
  ['docs/twenty/upstream/', 'mirrored upstream docs, see scripts/pull-twenty-docs.mjs'],
  ['temp_login.json', 'contains a credential'],
  ['.env.local', 'contains credentials'],
  ['.vercel/', 'local deploy state'],
  ['.scratch/', 'local scratch space'],
  ['node_modules/', 'dependencies'],
  ['dist/', 'build output'],
  ['backend/scripts/', 'one-off local schema helpers, see scripts/twenty-schema/README.md'],
];

let tracked;
try {
  tracked = execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .filter(Boolean);
} catch (error) {
  console.error('pre-push: could not run git ls-files, skipping scope check.');
  process.exit(0);
}

const violations = [];
for (const file of tracked) {
  const normalized = file.replace(/\\/g, '/');
  for (const [prefix, reason] of OUT_OF_SCOPE) {
    if (normalized === prefix || normalized.startsWith(prefix)) {
      violations.push(`${normalized}: out of scope (${reason})`);
      break;
    }
  }
}

if (violations.length > 0) {
  console.error('pre-push: FAIL - out-of-scope paths are tracked in git:');
  for (const violation of violations) console.error(`  - ${violation}`);
  console.error('\nTo remove one from the tracked tree without deleting it locally:');
  console.error('  git rm -r --cached <path>');
  console.error('The path is already listed in .gitignore, so it stays on disk and stops being committed.');
  process.exit(1);
}

console.log(`pre-push: OK - none of the ${OUT_OF_SCOPE.length} out-of-scope paths are tracked.`);
